// This component was generated by @sitecore-search/cli on Thu Dec 05 2024 09:54:01 GMT+0530 (India Standard Time)
 
import { usePreviewSearchActions } from '@sitecore-search/react';
import { PreviewSearch } from '@sitecore-search/ui';
 
import styles from './styles.module.css';
 
type SuggestionBlockProps = {
  items: Array<{
    text: string;
  }>;
  title: string;
  blockId: string;
  filterAttribute?: string;
  disabled?: boolean;
};
const SuggestionBlock = ({
  items,
  title,
  blockId,
  filterAttribute,
  disabled,
}: SuggestionBlockProps) => {
  const { onSuggestionClick } = usePreviewSearchActions();
  return (
    <>
      {items.length > 0 && (
        <PreviewSearch.SuggestionsGroup
          id={blockId}
          filterAttribute={filterAttribute}
          className={styles['sitecore-suggestion-group-root']}
        >
          {items.map(({ text }) => (
            <PreviewSearch.SuggestionTrigger
              id={text}
              key={text}
              disabled={disabled}
              asChild
              className={styles['sitecore-suggestion-group-trigger']}
            >
              <a
                onClick={() => {
                  onSuggestionClick({
                    name: blockId,
                    title,
                    value: text,
                    displayName: text,
                  });
                }}
              >
                {text}
              </a>
            </PreviewSearch.SuggestionTrigger>
          ))}
        </PreviewSearch.SuggestionsGroup>
      )}
    </>
  );
};
export default SuggestionBlock;
 