// This component was generated by @sitecore-search/cli on Mon Dec 23 2024 16:23:58 GMT+0000 (Coordinated Universal Time)

import styles from './styles.module.css';

type QueryResultsSummaryProps = {
  currentPage: number;
  itemsPerPage: number;
  totalItems: number;
  totalItemsReturned: number;
};
const QueryResultsSummary = ({
  currentPage,
  itemsPerPage,
  totalItems,
  totalItemsReturned,
}: QueryResultsSummaryProps) => {
  return (
    <div className={styles['sitecore-summary-wrapper']}>
      Showing {itemsPerPage * (currentPage - 1) + 1} -{' '}
      {itemsPerPage * (currentPage - 1) + totalItemsReturned} of {totalItems} results
    </div>
  );
};
export default QueryResultsSummary;
