/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.


import { ComponentBuilder } from '@sitecore-jss/sitecore-jss-nextjs';

import { BYOCWrapper, FEaaSWrapper } from '@sitecore-jss/sitecore-jss-nextjs';

import * as CdpPageView from 'src/components/CdpPageView';
import * as ColumnSplitter from 'src/components/ColumnSplitter';
import * as Container from 'src/components/Container';
import * as ContentBlock from 'src/components/ContentBlock';
import * as FEAASScripts from 'src/components/FEAASScripts';
import * as Image from 'src/components/Image';
import * as LinkList from 'src/components/LinkList';
import * as Navigation from 'src/components/Navigation';
import * as PageContent from 'src/components/PageContent';
import * as PartialDesignDynamicPlaceholder from 'src/components/PartialDesignDynamicPlaceholder';
import * as Promo from 'src/components/Promo';
import * as RichText from 'src/components/RichText';
import * as RowSplitter from 'src/components/RowSplitter';
import * as Title from 'src/components/Title';
import * as Carousel from 'src/components/Espire/Composites/Carousel';
import * as TabComponent from 'src/components/Espire/Composites/TabComponent';
import * as Cookie from 'src/components/Espire/Header/Cookie';
import * as LanguageSelector from 'src/components/Espire/Header/LanguageSelector';
import * as SearchBox from 'src/components/Espire/Header/SearchBox';
import * as Listing from 'src/components/Espire/Listing/Listing';
import * as Maps from 'src/components/Espire/Maps/Maps';
import * as ArticleBanner from 'src/components/Espire/PageContent/ArticleBanner';
import * as Banner from 'src/components/Espire/PageContent/Banner';
import * as HeadScript from 'src/components/Espire/PageContent/HeadScript';
import * as Link from 'src/components/Espire/PageContent/Link';
import * as PlainHTMLReusable from 'src/components/Espire/PageContent/PlainHTMLReusable';
import * as RichTextReusable from 'src/components/Espire/PageContent/RichTextReusable';
import * as Separator from 'src/components/Espire/PageStructure/Separator';
import * as Feeds from 'src/components/Espire/SocialSharing/Feeds';
import * as SocialMediaFeeds from 'src/components/Espire/SocialSharing/SocialMediaFeeds';
import * as SocialMediaShare from 'src/components/Espire/SocialSharing/SocialMediaShare';

export const components = new Map();
components.set('BYOCWrapper', BYOCWrapper);
components.set('FEaaSWrapper', FEaaSWrapper);

components.set('CdpPageView', CdpPageView);
components.set('ColumnSplitter', ColumnSplitter);
components.set('Container', Container);
components.set('ContentBlock', ContentBlock);
components.set('FEAASScripts', FEAASScripts);
components.set('Image', Image);
components.set('LinkList', LinkList);
components.set('Navigation', Navigation);
components.set('PageContent', PageContent);
components.set('PartialDesignDynamicPlaceholder', PartialDesignDynamicPlaceholder);
components.set('Promo', Promo);
components.set('RichText', RichText);
components.set('RowSplitter', RowSplitter);
components.set('Title', Title);
components.set('Carousel', Carousel);
components.set('TabComponent', TabComponent);
components.set('Cookie', Cookie);
components.set('LanguageSelector', LanguageSelector);
components.set('SearchBox', SearchBox);
components.set('Listing', Listing);
components.set('Maps', Maps);
components.set('ArticleBanner', ArticleBanner);
components.set('Banner', Banner);
components.set('HeadScript', HeadScript);
components.set('Link', Link);
components.set('PlainHTMLReusable', PlainHTMLReusable);
components.set('RichTextReusable', RichTextReusable);
components.set('Separator', Separator);
components.set('Feeds', Feeds);
components.set('SocialMediaFeeds', SocialMediaFeeds);
components.set('SocialMediaShare', SocialMediaShare);

export const componentBuilder = new ComponentBuilder({ components });

export const moduleFactory = componentBuilder.getModuleFactory();
