/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || '{51DC7C23-A175-4922-B021-282102C4893C}';
config.sitecoreApiHost = process.env.SITECORE_API_HOST || 'http://cm';
config.sitecoreSiteName = process.env.SITECORE_SITE_NAME || 'espire';
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || '/sitecore/api/graph/edge';
config.defaultLanguage = process.env.DEFAULT_LANGUAGE || 'en';
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || 'http://cm/sitecore/api/graph/edge';
config.layoutServiceConfigurationName = process.env.LAYOUT_SERVICE_CONFIGURATION_NAME || 'sxa-jss';
config.publicUrl = process.env.PUBLIC_URL || 'https://www.xmcloudpreview.localhost';
config.sitecoreEdgeUrl = process.env.SITECORE_EDGE_URL || 'https://edge-platform.sitecorecloud.io';
config.sitecoreEdgeContextId = process.env.SITECORE_EDGE_CONTEXT_ID || '38tuOghynfp1j93ZjihUO0';
config.sites = process.env.SITES || '[{"name":"espire","hostName":"*","language":"en"}]';
module.exports = config;