---
ID: "d2e64372-7464-4b7c-95db-9d9c795d27ff"
Parent: "eb5669bd-c7c5-4d8a-b5e1-7adf25a7c9b7"
Template: "eb5669bd-c7c5-4d8a-b5e1-7adf25a7c9b7"
Path: /sitecore/templates/Feature/Espire Accelerator/Espire Basic Components/Link Folder/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /~/icon/imaging/32x32/line_bezier_red_h.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {FA997AA3-4AD9-47C8-BA18-4AC9EC3C5F16}
    {EB5669BD-C7C5-4D8A-B5E1-7ADF25A7C9B7}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2b8fcd95-8dda-4795-9d31-4d6114c1601f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240108T053748Z
